### ISSUE TITLE
Add an explicit output operator

### ISSUE THREAD

**Issue by vihanb** [zachgates7/Gogh#3]
I don't know how to add it but my feature-request is an operator which outputs the TOS so I can output the TOS midway through the program.

so if the operator is `A` and I run:

``` bash
$ ./gogh no '1 2+A3+'
3
6
```

or there could be an alternative command which doesn't have a newline at the end.

**Comment by zachgates** [comment]
Added. See b3150c2f87c57aa8673fcaf7b6b23f549dbf5f50.

**Comment by vihanb** [comment]
\o/
